version: "3.9"


x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "myAwEsOm3pa55@w0rd"
  POSTGRES_USER: "user"

x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "1"
  # App
  APP_NAME: "data-aggregation-service"
  APP_VERSION: "1.0.0"
  # HTTP settings
  HTTP_PORT: "8080"
  HTTP_USE_PREFORK_MODE: "false"
  # Logger
  LOG_LEVEL: "debug"
  # PG
  PG_POOL_MAX: "2"
  PG_URL: "postgres://user:myAwEsOm3pa55@w0rd@db:5432/db"
  # gRPC
  GRPC_PORT: "8081"
  # Metrics
  METRICS_ENABLED: "true"
  # Swagger
  SWAGGER_ENABLED: "true"


services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_network:
        aliases:
          - db.lvh.me

  app:
    container_name: app
    platform: linux/amd64
    pid: "host"
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    networks:
      app_network:
        aliases:
          - app.lvh.me

  nginx:
    image: nginx:1.29.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      app_network:
        aliases:
          - nginx.lvh.me


networks:
  app_network:
    external: false


volumes:
  db_data:
