// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.20.3
// source: docs/proto/v1/packet.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MaxValue      int64                  `protobuf:"varint,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPacket) Reset() {
	*x = DataPacket{}
	mi := &file_docs_proto_v1_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPacket) ProtoMessage() {}

func (x *DataPacket) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPacket.ProtoReflect.Descriptor instead.
func (*DataPacket) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_packet_proto_rawDescGZIP(), []int{0}
}

func (x *DataPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataPacket) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataPacket) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

type FindPacketByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPacketByIDRequest) Reset() {
	*x = FindPacketByIDRequest{}
	mi := &file_docs_proto_v1_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPacketByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPacketByIDRequest) ProtoMessage() {}

func (x *FindPacketByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPacketByIDRequest.ProtoReflect.Descriptor instead.
func (*FindPacketByIDRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_packet_proto_rawDescGZIP(), []int{1}
}

func (x *FindPacketByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindPacketByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packet        *DataPacket            `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPacketByIDResponse) Reset() {
	*x = FindPacketByIDResponse{}
	mi := &file_docs_proto_v1_packet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPacketByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPacketByIDResponse) ProtoMessage() {}

func (x *FindPacketByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_packet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPacketByIDResponse.ProtoReflect.Descriptor instead.
func (*FindPacketByIDResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_packet_proto_rawDescGZIP(), []int{2}
}

func (x *FindPacketByIDResponse) GetPacket() *DataPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

type ListPacketsByPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPacketsByPeriodRequest) Reset() {
	*x = ListPacketsByPeriodRequest{}
	mi := &file_docs_proto_v1_packet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPacketsByPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPacketsByPeriodRequest) ProtoMessage() {}

func (x *ListPacketsByPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_packet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPacketsByPeriodRequest.ProtoReflect.Descriptor instead.
func (*ListPacketsByPeriodRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_packet_proto_rawDescGZIP(), []int{3}
}

func (x *ListPacketsByPeriodRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ListPacketsByPeriodRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ListPacketsByPeriodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataPacket          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPacketsByPeriodResponse) Reset() {
	*x = ListPacketsByPeriodResponse{}
	mi := &file_docs_proto_v1_packet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPacketsByPeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPacketsByPeriodResponse) ProtoMessage() {}

func (x *ListPacketsByPeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_packet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPacketsByPeriodResponse.ProtoReflect.Descriptor instead.
func (*ListPacketsByPeriodResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_packet_proto_rawDescGZIP(), []int{4}
}

func (x *ListPacketsByPeriodResponse) GetItems() []*DataPacket {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_docs_proto_v1_packet_proto protoreflect.FileDescriptor

const file_docs_proto_v1_packet_proto_rawDesc = "" +
	"\n" +
	"\x1adocs/proto/v1/packet.proto\x12\agrpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n" +
	"\n" +
	"DataPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tmax_value\x18\x03 \x01(\x03R\bmaxValue\"'\n" +
	"\x15FindPacketByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x16FindPacketByIDResponse\x12+\n" +
	"\x06packet\x18\x01 \x01(\v2\x13.grpc.v1.DataPacketR\x06packet\"|\n" +
	"\x1aListPacketsByPeriodRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"H\n" +
	"\x1bListPacketsByPeriodResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.grpc.v1.DataPacketR\x05items2\xc9\x01\n" +
	"\x12AggregationService\x12Q\n" +
	"\x0eFindPacketByID\x12\x1e.grpc.v1.FindPacketByIDRequest\x1a\x1f.grpc.v1.FindPacketByIDResponse\x12`\n" +
	"\x13ListPacketsByPeriod\x12#.grpc.v1.ListPacketsByPeriodRequest\x1a$.grpc.v1.ListPacketsByPeriodResponseB\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_packet_proto_rawDescOnce sync.Once
	file_docs_proto_v1_packet_proto_rawDescData []byte
)

func file_docs_proto_v1_packet_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_packet_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_packet_proto_rawDesc), len(file_docs_proto_v1_packet_proto_rawDesc)))
	})
	return file_docs_proto_v1_packet_proto_rawDescData
}

var file_docs_proto_v1_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_docs_proto_v1_packet_proto_goTypes = []any{
	(*DataPacket)(nil),                  // 0: grpc.v1.DataPacket
	(*FindPacketByIDRequest)(nil),       // 1: grpc.v1.FindPacketByIDRequest
	(*FindPacketByIDResponse)(nil),      // 2: grpc.v1.FindPacketByIDResponse
	(*ListPacketsByPeriodRequest)(nil),  // 3: grpc.v1.ListPacketsByPeriodRequest
	(*ListPacketsByPeriodResponse)(nil), // 4: grpc.v1.ListPacketsByPeriodResponse
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_docs_proto_v1_packet_proto_depIdxs = []int32{
	5, // 0: grpc.v1.DataPacket.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: grpc.v1.FindPacketByIDResponse.packet:type_name -> grpc.v1.DataPacket
	5, // 2: grpc.v1.ListPacketsByPeriodRequest.start:type_name -> google.protobuf.Timestamp
	5, // 3: grpc.v1.ListPacketsByPeriodRequest.end:type_name -> google.protobuf.Timestamp
	0, // 4: grpc.v1.ListPacketsByPeriodResponse.items:type_name -> grpc.v1.DataPacket
	1, // 5: grpc.v1.AggregationService.FindPacketByID:input_type -> grpc.v1.FindPacketByIDRequest
	3, // 6: grpc.v1.AggregationService.ListPacketsByPeriod:input_type -> grpc.v1.ListPacketsByPeriodRequest
	2, // 7: grpc.v1.AggregationService.FindPacketByID:output_type -> grpc.v1.FindPacketByIDResponse
	4, // 8: grpc.v1.AggregationService.ListPacketsByPeriod:output_type -> grpc.v1.ListPacketsByPeriodResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_packet_proto_init() }
func file_docs_proto_v1_packet_proto_init() {
	if File_docs_proto_v1_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_packet_proto_rawDesc), len(file_docs_proto_v1_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_packet_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_packet_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_packet_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_packet_proto = out.File
	file_docs_proto_v1_packet_proto_goTypes = nil
	file_docs_proto_v1_packet_proto_depIdxs = nil
}
